load("@pre-commit//pre-commit:defs.bzl", "pre_commit")

pre_commit(
   name = "pre_commit_hooks",
   # Use externally defined collection of hooks that provides `pre_commit_hooks` rule
   srcs = ["@pre-commit-hooks"],
)
